cmake -G $1 -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON -DENABLE_SANITIZERS=ON     \
      -DENABLE_SANITIZER_LEAK=ON  -DENABLE_SANITIZER_ADDRESS=ON                      \
      -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON -DENABLE_CCACHE=ON -DENABLE_TESTS=ON  \
      -S . -B ./build